// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Article struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	URL       string    `json:"url"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Source    *Source   `json:"source"`
}

type CreateArticleInput struct {
	Title    string `json:"title"`
	URL      string `json:"url"`
	SourceID string `json:"sourceId"`
}

type Source struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
